### ISSUE TITLE
Docs: 이슈 템플릿, 도큐먼트 정리

### ISSUE THREAD

**Issue by yeniful** [kko-okk/kko_okk#250]
### Motivation
- 로컬 문서나 노션에 저장되어있던 문서들이 분산되어있어서 Wiki에 모아두는 작업을 할 예정입니다.

### Todo
- [x] 컨벤션 문서를 Wiki로 옮기는 작업을 합니다.
- [x] 이슈템플릿 보완을 합니다.
- [x] 리드미의 스크립트를 Wiki로 옮기는 작업을 합니다.

**Comment by garlicvread** [comment]
위키 작업이 험난하니만큼 같이 으쌰으쌰 열심히 작업해 보아용!
